name: CI - Test/Lint

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [ '14' ]
    name: ${{ matrix.node }} - test unit and lint
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install npm dependencies
        run: npm install
      
      - name: Build
        run: npm run build
      
      - name: Run tests and lint
        run: npm run check
        
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info # optional (default value)

      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true